// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY7VjlfPal5_WrFG4wpVCiNBJdyqUl5m8',
    appId: '1:191812159847:web:e3df4f49cbd01e653847c2',
    messagingSenderId: '191812159847',
    projectId: 'reddit-e1d33',
    authDomain: 'reddit-e1d33.firebaseapp.com',
    storageBucket: 'reddit-e1d33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc21XdLgCmgujRQrvmtnzRc4zGISl5JLs',
    appId: '1:191812159847:android:26ee6f6e19a494f83847c2',
    messagingSenderId: '191812159847',
    projectId: 'reddit-e1d33',
    storageBucket: 'reddit-e1d33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIAPk1rne3xCFnMz3VC0FBWg3E92aSSOY',
    appId: '1:191812159847:ios:44bfcbb2f9c927fb3847c2',
    messagingSenderId: '191812159847',
    projectId: 'reddit-e1d33',
    storageBucket: 'reddit-e1d33.appspot.com',
    iosClientId: '191812159847-u9h0g2umq20tl0s04in3sql5ahtp7di4.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
